#!/bin/bash
# converting all files to utf8


DIR=$1
USR=$2
GRP=$3
EXE=$4

echo "$DIR $USR $GRP $EXE"

for f in `/usr/bin/find $DIR -name "*.php"`
do
    if [ "/usr/bin/test -f $f" ]; then
        CHARSET="$( /usr/bin/file -bi "$f"|/usr/bin/awk -F "=" '{print $2}')"
        echo -n "$f ($CHARSET)"

        if [ "$CHARSET" != "utf-8" ]; then
        	if [ "$EXE" != "XX" ]; then
           	    echo -n " Converting "
  	      	    /usr/bin/iconv -f "$CHARSET" -t utf8 "$f" -o "$f".utf8 && mv -f "$f".utf8 "$f" && echo -n "OK"
  	      	else
           	    echo -n " Converting (DEMO)"
  	      	fi
  	    fi
        echo ""
    else
        echo "Skipping $f - it's a regular file";
    fi
done

if [ "$EXE" != "XX" ]; then
	echo ""
	echo "OWNERSHIP";
	/bin/chown -Rv $USR.$GRP $DIR;

	echo ""
	echo "MOD 755";
	/usr/bin/find $DIR -name "*.php" -exec chmod 755 \{\} \; -print;
fi

echo ""
