#!/bin/bash
# converting all files to utf8 

   red="\033[31m";
  blue="\033[34m";
 green="\033[32m";
yellow="\033[33m";
 reset="\033[0m";

DIR=`pwd`
#"$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR;
echo "JE SUIS DANS $DIR"
#exit;

for f in `find . -name "*.php"`
#for f in *.php
do
    if [ "test -f $f" ]; then
        CHARSET="$( file -bI "$f"|awk -F "=" '{print $2}')"
        echo -ne "$blue" "$f" "$reset"

        if [ "$CHARSET" != "utf-8" ]; then
        	echo -ne "IS $green $CHARSET $reset";
  	      	echo -n "Converting $f "
            iconv -f "$CHARSET" -t utf8 "$f" > "$f".utf8 && mv -f "$f".utf8 "$f" && echo -n "OK"
        fi
        echo ""
    else
        echo "Skipping $f - it's a regular file";
    fi
done

echo ""
echo ""
echo ""
echo ""